A large functionality extention :)
commince/voleyball-game pull request #1
Opened 2020-11-18 15:24 UTC by ViktorKVG

Добавлены:
1. Возможность загрузки игроков, а также команд целиком из БД
2. Возможность сохранения в БД, созданных вручную команд

2020-11-18 19:14 UTC, commince requested changes

2020-11-18 19:14 UTC, commince commented on 123.txt
> -12321
Переименуй в readme.md.
Это стандарт:)
https://ru.wikipedia.org/wiki/Markdown

А в самом файле написать можно

# This is a readMe file!! 


тогда даже в гитхабе красиво отобразится оно

2020-11-18 19:14 UTC, commince commented on 123.txt
> -12321
(если решетку перед строкой поставишь - отобразится как заголовок)

2020-11-18 19:14 UTC, commince commented on DBPlayerBuilder.java
> +            resultSet = new DBQuerries().implementQuerry("SELECT player_name, player_serve, player_attack\n" +
А зачем тебе здесь try-catch? ты всё перехватываешь внутри implementQuerry

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +    public ResultSet implementQuerry(String querryText) {
implementQuery (1 r)

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +
лишний некрасивый перенос

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +
перенос убери::)

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +            Class.forName("org.postgresql.Driver");
"org.postgresql.Driver" - в static final константу

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +            e.printStackTrace();
простое проглатывание ошибки без действий - плохой стиль. Надо ресурс закрывать, чтобы не было утечки, либо кидать Runtime - исключение, чтобы прога закрылась. А лучше сделать всё в стиле try-with-resources.

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +        return "jdbc:postgresql://127.0.0.1:5432/volley_teams";
В константу

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +        return "postgres";
в константу

2020-11-18 19:14 UTC, commince commented on DBQuerries.java
> +        return "LENIN1988";
аналогично

2020-11-18 19:14 UTC, commince commented on DBTeamBuilder.java
> +import java.sql.*;
star import - плохой стиль. Надо импорты указывать явно

2020-11-18 19:14 UTC, commince commented on DBTeamSaver.java
> +                dbQuerries.executeUpdate("INSERT INTO Players(team_id, player_name, player_serve, player_attack)\n" +
\n не нужен

2020-11-18 19:14 UTC, commince commented on DBTeamSaver.java
> +                dbQuerries.executeUpdate("INSERT INTO Players(team_id, player_name, player_serve, player_attack)\n" +
вместо него - пробел

2020-11-18 19:14 UTC, commince commented on DBTeamSaver.java
> +    private void saveTeamSquad(List teamSquad, String teamName) {
List без дженерика

2020-11-18 19:14 UTC, commince commented on DBTeamSaver.java
> +            player = (Player) teamSquad.get(i);
Будет дженерик - не надо будет кастов

2020-11-20 14:11 UTC, ViktorKVG commented on DBQuerries.java
> +            e.printStackTrace();
Чтобы не дублировать код, я вывел открытие и закрытие ресурса в разные методы (getConnection() и closeConnection()). Получается, что в getConnection() использовать try-with-resources, ресурс закроется до того, как мы его используем в методах implementQuery() и executeUpdate(). Получается, я сделал неправильно? Необходимо каждый раз прописывать содержимое getConnection() внутри методов implementQuery() и executeUpdate()?

2020-11-23 21:47 UTC, commince commented on DBQuerries.java
> +            e.printStackTrace();
Ну ок, насчет try-with-resources - можно сделать красиво, но мы не будем:)
Давай просто обработаем случаи, когда у тебя может выкинуться ошибка, и ресурс не освободится.
https://habr.com/ru/post/178405/
вот кстати хорошая статья на эту тему

2020-11-25 09:43 UTC, ViktorKVG commented on DBQuerries.java
> +            e.printStackTrace();
Дрюха, залил новую версию "DBQueries", как будет возможность, глянь, плиз? Если все правильно понял, сейчас реализовал логику: если возникают проблемы с подключением (!(connectionTrouble == null)) - закрываем соединение, если оно успело открыться (if (conn != null) conn.close()).

2021-04-05 09:21 UTC, commince approved these changes

2021-04-05 09:22 UTC, commince requested changes
старый ПР, можно убить его просто

2021-04-09 13:49 UTC, closed without merging

2021-04-09 13:49 UTC, ViktorKVG commented
Старый ПР, убит)